chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('join_room/', views.rooms, name='rooms'),
    path('', views.options, name = 'options' ),
    path('create_room/', views.create_chat_room, name = 'create'),
    path('<slug:slug>/', views.room, name='room'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.frontpage, name='frontpage'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

uschat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('rooms/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models

class Room(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

core/models.py
from django.db import models

# Create your models here.

chat/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Room
from django.forms import ModelForm


class ChatRoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['name', 'slug']

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from .forms import ChatRoomForm

from .models import Room, Message

@login_required
def rooms(request):
    rooms = Room.objects.all()

    return render(request, 'chat/rooms.html', {'rooms': rooms})

@login_required
def room(request, slug):
    room = Room.objects.get(slug=slug)
    messages = Message.objects.filter(room=room)[0:25]

    return render(request, 'chat/room.html', {'room': room, 'messages': messages})


def options(request):
    return render(request, 'chat/choose.html')



@login_required
def create_chat_room(request):
    if request.method == 'POST':
        form = ChatRoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rooms')  # Redirect to a success page
    else:
        form = ChatRoomForm()

    return render(request, 'chat/createroom.html', {'form': form})

core/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect

from .forms import SignUpForm

def frontpage(request):
    return render(request, 'core/frontpage.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('frontpage')
    else:
        form = SignUpForm()
    
    return render(request, 'core/signup.html', {'form': form})

chat/templates/chat/choose.html
<!-- index.html -->

{% extends 'core/base.html' %}

{% block title %}Chat Room Options{% endblock %}

{% block content %}
<div class="flex justify-center items-center h-screen">
    <div class="text-center">
        <h1 class="text-4xl font-bold mb-8">Choose an Option</h1>
        <div class="flex space-x-4">
            <!-- Create Room Option -->
            <a href="/rooms/create_room/" class="px-6 py-3 rounded-full bg-green-500 hover:bg-green-600 text-white flex items-center">
                <span class="mr-2 text-2xl">&#43;</span> CREATE ROOM
            </a>
            
            <!-- Join Room Option -->
            <a href="/rooms/join_room/" class="px-6 py-3 rounded-full bg-blue-500 hover:bg-blue-600 text-white flex items-center">
                <span class="mr-2 text-2xl">&#128197;</span> JOIN ROOM
            </a>
        </div>
    </div>
</div>
{% endblock %}

chat/templates/chat/createroom.html
<!-- create_chat_room.html -->

{% extends 'core/base.html' %}

{% block content %}
<div class="flex justify-center items-center h-screen">
    <div class="bg-white p-16 rounded-lg shadow-md w-96">
        <h2 class="text-3xl font-bold mb-8">Create a Chat Room</h2>
        <form method="post" action="{% url 'create' %}" class="space-y-4">
            {% csrf_token %}
            <div>
                <label for="id_name" class="block text-sm font-medium text-gray-600 mb-2">Room Name</label>
                {{ form.name}}
            </div>
            <div>
                <label for="id_slug" class="block text-sm font-medium text-gray-600 mb-2">Slug</label>
                {{ form.slug}}
            </div>
            <button type="submit" class="px-6 py-3 rounded-full bg-blue-500 text-white hover:bg-blue-600">Create Room</button>
        </form>
    </div>
</div>
{% endblock %}

chat/templates/chat/room.html
{% extends 'core/base.html' %}

{% block title %}{{ room.name }} | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">{{ room.name }}</h1>
</div>

<div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl shadow-md">
    <div class="chat-messages space-y-3 overflow-y-auto max-h-96" id="chat-messages">
        {% for m in messages %}
            <div class="flex items-start mb-2">
                <div class="ml-3 bg-gray-100 p-4 rounded-md shadow-md">
                    <span class="text-teal-600 font-bold">{{ m.user.username }}</span>
                    <p class="text-gray-800">{{ m.content }}</p>
                </div>                
            </div>
        {% endfor %}
    </div>
</div>


<div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded-xl shadow-md">
    <form method="post" action="." class="flex">
        <input type="text" name="content" class="flex-1 mr-3 px-4 py-2 rounded-md border border-gray-300" placeholder="Your message..." id="chat-message-input">

        <button 
            class="px-5 py-3 rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none shadow-md"
            id="chat-message-submit"
        >Submit</button>
    </form>
</div>
{% endblock %}

{% block scripts %}
{{ room.slug|json_script:"json-roomname" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + roomName
        + '/'
    );

    chatSocket.onclose = function(e) {
        console.log('onclose');
    }

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);

        if (data.message) {
            document.querySelector('#chat-messages').innerHTML += ('<div class="flex items-start mb-2">' +
                '<div class="ml-3">' +
                '<span class="text-gray-600">' + data.username + '</span>' +
                '<p class="text-black">' + data.message + '</p>' +
                '</div>' +
                '</div>');
        } else {
            alert('The message was empty!');
        }

        scrollToBottom();
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault()

        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'message': message,
            'username': userName,
            'room': roomName
        }));

        messageInputDom.value = '';

        return false;
    };

    function scrollToBottom() {
        let objDiv = document.getElementById("chat-messages");
        objDiv.scrollTop = objDiv.scrollHeight;
    }

    scrollToBottom();
</script>
{% endblock %}

chat/templates/chat/rooms.html
<!-- Your HTML template -->

{% extends 'core/base.html' %}

{% block title %}Rooms | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">  
    <h1 class="text-3xl lg:text-6xl text-white">Rooms</h1>
</div>

<div class="w-full flex flex-wrap items-center">
    {% for room in rooms %}
        <div class="w-full lg:w-1/4 px-3 py-3">
            <div class="p-4 bg-white shadow rounded-xl text-center">
                <h2 class="mb-5 text-2xl font-semibold">{{ room.name }}</h2>

                <a href="{% url 'room' room.slug %}" class="px-6 py-4 block rounded-full text-white bg-green-500 hover:bg-green-600">Join</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Djangochat{% endblock %}</title>

    <!-- Tailwind CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

    <style>
        /* Additional custom styles */
        body {
            background: linear-gradient(to right, #7F7FD5, #86A8E7, #91EAE4);
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; /* Choose a distinct font */
            color: #2d3748; /* Set the text color to a dark gray */
        }

        .messages {
            max-height: 400px;
            overflow-y: auto;
        }

        /* Set the text color for links */
        a {
            color: #4299e1; /* Set link color to a blue shade */
        }

        /* Set the text color for hover effects on links */
        a:hover {
            color: #3182ce; /* Set hover color to a slightly darker blue */
        }
    </style>
</head>

<body class="font-sans antialiased">
    <nav class="flex items-center justify-between px-4 py-6 bg-teal-800">
        <div>
            <a href="/" class="text-xl font-bold text-gray-800">Djangochat</a>
        </div>

        <div class="flex items-center space-x-4">
            {% if request.user.is_authenticated %}
                <a href="/rooms/" class="text-white hover:text-gray-300">Rooms</a>
                <a href="/logout/" class="px-4 py-2 rounded text-teal-900 bg-teal-300 hover:bg-teal-500">Log out</a>
            {% else %}
                <a href="/login/" class="text-white hover:text-gray-300">Log in</a>
                <a href="/signup/" class="px-4 py-2 rounded text-teal-900 bg-teal-300 hover:bg-teal-500">Sign up</a>
            {% endif %}
        </div>
    </nav>

    <div class="mx-auto my-8 p-4">
        {% block content %}
        {% endblock %}
    </div>

    {% block scripts %}
    <!-- Additional scripts go here -->
    {% endblock %}
</body>
</html>

core/templates/core/frontpage.html
{% extends 'core/base.html' %}

{% block title %}Welcome | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white font-semibold">Djangochat</h1>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Log in</h1>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>

        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>

        <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %} 
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <button class="px-6 py-3 rounded-full text-white bg-indigo-600 hover:bg-indigo-700 transition duration-300 ease-in-out shadow-lg">Submit</button>
</form>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-6xl text-white">Sign up</h1>
</div>

<form method="post" action="." class="lg:w-1/4 px-4 mx-auto">
    {% csrf_token %}

    <div class="mb-5">
        <label class="text-white">Username</label>

        <input type="text" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Password</label>

        <input type="password" name="password1" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label class="text-white">Repeat password</label>

        <input type="password" name="password2" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %} 
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <button class="px-6 py-3 rounded-full text-white bg-indigo-600 hover:bg-indigo-700 transition duration-300 ease-in-out shadow-lg">Submit</button>

</form>
{% endblock %}